### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by georgemilosh** [ZichaoLong/PDE-Net#12]
I followed the readme installing the required documentation but when executing 
```
python train.py --name=${casename} --configfile=checkpoint/${casename}/options.yaml
```
got this error:
```
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    globalnames, callback, model, data_model, sampling, addnoise = setenv.setenv(options)
  File "/net/nfs/ssd1/gmiloshe/PDE-Net/setenv.py", line 68, in setenv
    globalnames, callback, model = _set_model(options)
  File "/net/nfs/ssd1/gmiloshe/PDE-Net/setenv.py", line 45, in _set_model
    model.to(globalnames['device'])
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 205, in _apply
    self._buffers[key] = fn(buf)
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/net/nfs/ssd1/miniconda3/envs/PDE-Net-2/lib/python3.7/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by georgemilosh** [comment]
I tried more modern version of torch and was able to run the code
