### ISSUE TITLE
Train PDE-Net using CPU

### ISSUE THREAD

**Issue by AbbyYangbb** [ZichaoLong/PDE-Net#2]
Hi! Thank you for reading this! 

While running your code, I got following error:

$ python learn_variantcoelinear2d.py
Traceback (most recent call last):
  File "learn_variantcoelinear2d.py", line 36, in <module>
    namestobeupdate, callback, linpdelearner = linpdeconfig.setenv(options)
  File "/Users/Downloads/PDE_NET/PDE-Net/linpdeconfig.py", line 210, in setenv
    linpdelearner.cuda(namestobeupdate['gpu'])
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 197, in _apply
    self._buffers[key] = fn(buf)
  File "/Users/anaconda3/envs/pdenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

I was wondering whether I can train a PDE-Net using CPU? Or it will be preferred to get a CUDA GPU to run this?

**Comment by chenxingqiang** [comment]
by setup —gpu ,-1

**Comment by AbbyYangbb** [comment]
> by setup —gpu ,-1

I will try it. Thank you very much!
